dotenv: .env

compiler:
  solc:
    version: 0.8.20

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.9.6

networks:
  default: development
  development:
    host: http://127.0.0.1
    cmd_settings:
      accounts: 10
  polygon-amoy:
    chainid: 80002
