export const CONTRACT_ABI = [
  {
    type: 'function',
    name: 'registerIssuer',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'issuer', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'issueCredential',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'candidate', type: 'address' },
      { name: 'candidateName', type: 'string' },
      { name: 'degree', type: 'string' },
      { name: 'institution', type: 'string' },
      { name: 'issueDate', type: 'uint256' },
      { name: 'expiryDate', type: 'uint256' },
      { name: 'ipfsCid', type: 'string' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'verifyCredential',
    stateMutability: 'view',
    inputs: [{ name: 'credentialId', type: 'uint256' }],
    outputs: [
      { name: 'exists', type: 'bool' },
      { name: 'valid', type: 'bool' },
      { name: 'revoked', type: 'bool' },
      { name: 'expired', type: 'bool' },
      { name: 'candidate', type: 'address' },
      { name: 'issuer', type: 'address' },
      { name: 'candidateName', type: 'string' },
      { name: 'degree', type: 'string' },
      { name: 'institution', type: 'string' },
      { name: 'issueDate', type: 'uint256' },
      { name: 'expiryDate', type: 'uint256' },
      { name: 'ipfsCid', type: 'string' },
    ],
  },
  {
    type: 'function',
    name: 'revokeCredential',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'credentialId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'getCredentialIdsByWallet',
    stateMutability: 'view',
    inputs: [{ name: 'wallet', type: 'address' }],
    outputs: [{ name: '', type: 'uint256[]' }],
  },
];
